version: "3.9"
services:
  backend:
    image: signalr-omagol_backend
    ports:
      - "8000:80"
    networks:
      - serviceNetwork
  
  viteapp:
    image: signalr-omagol_viteapp
    ports:
      - "5000:80"
    env_file:
      - .env
    networks:
      - serviceNetwork

networks:
  serviceNetwork:


