version: "3.9"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"

